package com.edalac.inventario.dto;
// default package
// Generated 29-jun-2016 21:10:30 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TbCiudad generated by hbm2java
 */
public class TbCiudad implements java.io.Serializable {

	private long nbIdciudad;
	private TbDepartamento tbDepartamento;
	private String vrNombre;
	private Set tbTerceros = new HashSet(0);

	public TbCiudad() {
	}

	public TbCiudad(long nbIdciudad, TbDepartamento tbDepartamento, String vrNombre) {
		this.nbIdciudad = nbIdciudad;
		this.tbDepartamento = tbDepartamento;
		this.vrNombre = vrNombre;
	}

	public TbCiudad(long nbIdciudad, TbDepartamento tbDepartamento, String vrNombre, Set tbTerceros) {
		this.nbIdciudad = nbIdciudad;
		this.tbDepartamento = tbDepartamento;
		this.vrNombre = vrNombre;
		this.tbTerceros = tbTerceros;
	}

	public long getNbIdciudad() {
		return this.nbIdciudad;
	}

	public void setNbIdciudad(long nbIdciudad) {
		this.nbIdciudad = nbIdciudad;
	}

	public TbDepartamento getTbDepartamento() {
		return this.tbDepartamento;
	}

	public void setTbDepartamento(TbDepartamento tbDepartamento) {
		this.tbDepartamento = tbDepartamento;
	}

	public String getVrNombre() {
		return this.vrNombre;
	}

	public void setVrNombre(String vrNombre) {
		this.vrNombre = vrNombre;
	}

	public Set getTbTerceros() {
		return this.tbTerceros;
	}

	public void setTbTerceros(Set tbTerceros) {
		this.tbTerceros = tbTerceros;
	}

}
