package com.edalac.inventario.dto;
// default package
// Generated 29-jun-2016 21:10:30 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * TbDetalleFactura generated by hbm2java
 */
public class TbDetalleFactura implements java.io.Serializable {

	private long nbIdDetalle;
	private TbArticulo tbArticulo;
	private Long nbFactura;
	private Integer nbCantidad;
	private BigDecimal nbValorUnitario;
	private BigDecimal nbValorIva;
	private BigDecimal nbValorDescuento;

	public TbDetalleFactura() {
	}

	public TbDetalleFactura(long nbIdDetalle) {
		this.nbIdDetalle = nbIdDetalle;
	}

	public TbDetalleFactura(long nbIdDetalle, TbArticulo tbArticulo, Long nbFactura, Integer nbCantidad,
			BigDecimal nbValorUnitario, BigDecimal nbValorIva, BigDecimal nbValorDescuento) {
		this.nbIdDetalle = nbIdDetalle;
		this.tbArticulo = tbArticulo;
		this.nbFactura = nbFactura;
		this.nbCantidad = nbCantidad;
		this.nbValorUnitario = nbValorUnitario;
		this.nbValorIva = nbValorIva;
		this.nbValorDescuento = nbValorDescuento;
	}

	public long getNbIdDetalle() {
		return this.nbIdDetalle;
	}

	public void setNbIdDetalle(long nbIdDetalle) {
		this.nbIdDetalle = nbIdDetalle;
	}

	public TbArticulo getTbArticulo() {
		return this.tbArticulo;
	}

	public void setTbArticulo(TbArticulo tbArticulo) {
		this.tbArticulo = tbArticulo;
	}

	public Long getNbFactura() {
		return this.nbFactura;
	}

	public void setNbFactura(Long nbFactura) {
		this.nbFactura = nbFactura;
	}

	public Integer getNbCantidad() {
		return this.nbCantidad;
	}

	public void setNbCantidad(Integer nbCantidad) {
		this.nbCantidad = nbCantidad;
	}

	public BigDecimal getNbValorUnitario() {
		return this.nbValorUnitario;
	}

	public void setNbValorUnitario(BigDecimal nbValorUnitario) {
		this.nbValorUnitario = nbValorUnitario;
	}

	public BigDecimal getNbValorIva() {
		return this.nbValorIva;
	}

	public void setNbValorIva(BigDecimal nbValorIva) {
		this.nbValorIva = nbValorIva;
	}

	public BigDecimal getNbValorDescuento() {
		return this.nbValorDescuento;
	}

	public void setNbValorDescuento(BigDecimal nbValorDescuento) {
		this.nbValorDescuento = nbValorDescuento;
	}

}
