package com.edalac.inventario.dto;
// default package
// Generated 29-jun-2016 21:10:30 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TbEmpresa generated by hbm2java
 */
public class TbEmpresa implements java.io.Serializable {

	private long nbIdempresa;
	private String vrNombreEmpresa;
	private String vrCodigoEmpresa;
	private Set tbArticulos = new HashSet(0);

	public TbEmpresa() {
	}

	public TbEmpresa(long nbIdempresa) {
		this.nbIdempresa = nbIdempresa;
	}

	public TbEmpresa(long nbIdempresa, String vrNombreEmpresa, String vrCodigoEmpresa, Set tbArticulos) {
		this.nbIdempresa = nbIdempresa;
		this.vrNombreEmpresa = vrNombreEmpresa;
		this.vrCodigoEmpresa = vrCodigoEmpresa;
		this.tbArticulos = tbArticulos;
	}

	public long getNbIdempresa() {
		return this.nbIdempresa;
	}

	public void setNbIdempresa(long nbIdempresa) {
		this.nbIdempresa = nbIdempresa;
	}

	public String getVrNombreEmpresa() {
		return this.vrNombreEmpresa;
	}

	public void setVrNombreEmpresa(String vrNombreEmpresa) {
		this.vrNombreEmpresa = vrNombreEmpresa;
	}

	public String getVrCodigoEmpresa() {
		return this.vrCodigoEmpresa;
	}

	public void setVrCodigoEmpresa(String vrCodigoEmpresa) {
		this.vrCodigoEmpresa = vrCodigoEmpresa;
	}

	public Set getTbArticulos() {
		return this.tbArticulos;
	}

	public void setTbArticulos(Set tbArticulos) {
		this.tbArticulos = tbArticulos;
	}

}
