package com.edalac.inventario.dto;
// default package
// Generated 29-jun-2016 21:10:30 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TbEstado generated by hbm2java
 */
public class TbEstado implements java.io.Serializable {

	private long nbIdestado;
	private String vrDescripcion;
	private Set tbTerceros = new HashSet(0);

	public TbEstado() {
	}

	public TbEstado(long nbIdestado, String vrDescripcion) {
		this.nbIdestado = nbIdestado;
		this.vrDescripcion = vrDescripcion;
	}

	public TbEstado(long nbIdestado, String vrDescripcion, Set tbTerceros) {
		this.nbIdestado = nbIdestado;
		this.vrDescripcion = vrDescripcion;
		this.tbTerceros = tbTerceros;
	}

	public long getNbIdestado() {
		return this.nbIdestado;
	}

	public void setNbIdestado(long nbIdestado) {
		this.nbIdestado = nbIdestado;
	}

	public String getVrDescripcion() {
		return this.vrDescripcion;
	}

	public void setVrDescripcion(String vrDescripcion) {
		this.vrDescripcion = vrDescripcion;
	}

	public Set getTbTerceros() {
		return this.tbTerceros;
	}

	public void setTbTerceros(Set tbTerceros) {
		this.tbTerceros = tbTerceros;
	}

}
