package com.edalac.inventario.dto;
// default package
// Generated 29-jun-2016 21:10:30 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TbPais generated by hbm2java
 */
public class TbPais implements java.io.Serializable {

	private long nbIdpais;
	private String vrNombre;
	private Set tbDepartamentos = new HashSet(0);

	public TbPais() {
	}

	public TbPais(long nbIdpais, String vrNombre) {
		this.nbIdpais = nbIdpais;
		this.vrNombre = vrNombre;
	}

	public TbPais(long nbIdpais, String vrNombre, Set tbDepartamentos) {
		this.nbIdpais = nbIdpais;
		this.vrNombre = vrNombre;
		this.tbDepartamentos = tbDepartamentos;
	}

	public long getNbIdpais() {
		return this.nbIdpais;
	}

	public void setNbIdpais(long nbIdpais) {
		this.nbIdpais = nbIdpais;
	}

	public String getVrNombre() {
		return this.vrNombre;
	}

	public void setVrNombre(String vrNombre) {
		this.vrNombre = vrNombre;
	}

	public Set getTbDepartamentos() {
		return this.tbDepartamentos;
	}

	public void setTbDepartamentos(Set tbDepartamentos) {
		this.tbDepartamentos = tbDepartamentos;
	}

}
