package com.edalac.inventario.dto;
// default package
// Generated 29-jun-2016 21:10:30 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TbTipopersona generated by hbm2java
 */
public class TbTipopersona implements java.io.Serializable {

	private long nbIdtipopersona;
	private String vrDescripcion;
	private Set tbTerceros = new HashSet(0);

	public TbTipopersona() {
	}

	public TbTipopersona(long nbIdtipopersona, String vrDescripcion) {
		this.nbIdtipopersona = nbIdtipopersona;
		this.vrDescripcion = vrDescripcion;
	}

	public TbTipopersona(long nbIdtipopersona, String vrDescripcion, Set tbTerceros) {
		this.nbIdtipopersona = nbIdtipopersona;
		this.vrDescripcion = vrDescripcion;
		this.tbTerceros = tbTerceros;
	}

	public long getNbIdtipopersona() {
		return this.nbIdtipopersona;
	}

	public void setNbIdtipopersona(long nbIdtipopersona) {
		this.nbIdtipopersona = nbIdtipopersona;
	}

	public String getVrDescripcion() {
		return this.vrDescripcion;
	}

	public void setVrDescripcion(String vrDescripcion) {
		this.vrDescripcion = vrDescripcion;
	}

	public Set getTbTerceros() {
		return this.tbTerceros;
	}

	public void setTbTerceros(Set tbTerceros) {
		this.tbTerceros = tbTerceros;
	}

}
