package com.edalac.inventario.dto;
// default package
// Generated 29-jun-2016 21:10:30 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TbTipodocumento generated by hbm2java
 */
public class TbTipodocumento implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private long ndIdTipoDocumento;
	private String vrNombre;
	private String vrDescripcion;
	private Set tbTerceros = new HashSet(0);

	public TbTipodocumento() {
	}

	public long getNdIdTipoDocumento() {
		return this.ndIdTipoDocumento;
	}

	public void setNdIdTipoDocumento(long ndIdTipoDocumento) {
		this.ndIdTipoDocumento = ndIdTipoDocumento;
	}

	public String getVrNombre() {
		return vrNombre;
	}

	public void setVrNombre(String vrNombre) {
		this.vrNombre = vrNombre;
	}

	public String getVrDescripcion() {
		return this.vrDescripcion;
	}

	public void setVrDescripcion(String vrDescripcion) {
		this.vrDescripcion = vrDescripcion;
	}

	public Set getTbTerceros() {
		return this.tbTerceros;
	}

	public void setTbTerceros(Set tbTerceros) {
		this.tbTerceros = tbTerceros;
	}

}
